import type { ClaimInfo } from "./claimInfo";
import { lossTypeLabel } from "./claimInfo";

/** One label/value pair in a Job Information group. `value` is null/empty for "not yet known" — renders as an em dash. */
export interface JobInfoField {
  label: string;
  value: string | number | null;
}

export interface JobInfoGroup {
  title: string;
  fields: JobInfoField[];
}

/**
 * The inspection report's "Job Information" block, grouped for the redesigned layout — see
 * `components/JobInformationSection.tsx` (on-screen) and `pdf.ts`'s `drawJobInformation` (PDF
 * export), both of which render this same data instead of each keeping their own field list.
 *
 * Every field here comes straight from `ClaimInfo` — as of the Job Information redesign, none of
 * it is generated by the document-generation model any more (see documentGenerationPrompt.ts's
 * INSPECTION_REPORT_SECTION doc comment for why: every one of these 13 fields is already known
 * client-side with full fidelity before generation ever runs, so round-tripping it through the
 * model's text output only added risk — see "Date of Loss never reached the document," round 6).
 *
 * "PM Phone" and "Date/Time Contacted" have no data source yet in this Phase 1 prototype (same
 * profiles/login gap noted throughout claimInfo.ts) — they always render as "not yet known" here
 * so the screen and the PDF show the same explicit em dash rather than silently differing.
 */
export function buildJobInformationGroups(claim: ClaimInfo): JobInfoGroup[] {
  return [
    {
      title: "Property & Claim",
      fields: [
        { label: "Insured", value: claim.customerName },
        { label: "Address", value: claim.address },
        { label: "Claim Number", value: claim.claimNumber },
        { label: "Insurer", value: claim.insurer },
        { label: "Year of Building", value: claim.yearOfBuilding },
      ],
    },
    {
      title: "Loss Classification",
      fields: [
        { label: "Loss Type", value: lossTypeLabel(claim) },
        // "N/A" (not null/em dash) for a non-water claim — this is a deliberate "doesn't apply," not
        // a "not yet known." See ClaimInfo.lossType's doc comment.
        { label: "Category of Loss", value: claim.lossType !== null && claim.lossType !== "WATER" ? "N/A" : claim.waterCategory },
        { label: "Class of Loss", value: claim.lossType !== null && claim.lossType !== "WATER" ? "N/A" : claim.waterClass },
        { label: "Date of Loss", value: claim.dateOfLoss },
      ],
    },
    {
      title: "Contact & Timing",
      fields: [
        { label: "Project Manager", value: claim.pmName },
        { label: "PM Phone", value: null },
        { label: "Date/Time Contacted", value: null },
        { label: "Date/Time Inspected", value: claim.dateTimeInspected },
      ],
    },
  ];
}
