"""
The Scrivn Scan how-to drawings (the app's res/drawable/howto_*.xml vector drawables) for the tester
guide at /scan-guide, so the page and the app show the same pictures. Run again when the app's
drawings change:

    python scripts/howto-svgs.py

Reads ../ARCapturePrototype/android/app/src/main/res/drawable and writes
components/scanGuide/howtoDrawings.ts, which the guide renders inline (a file under public/ would sit
behind the sign-in gate in middleware.ts, and inline needs nothing fetched). Only what those files use
is converted: <path> with pathData, fill/stroke colours, stroke width, line cap and join, fillAlpha.
"""
import glob
import io
import json
import os
import xml.etree.ElementTree as ET

A = '{http://schemas.android.com/apk/res/android}'
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', 'ARCapturePrototype', 'android', 'app', 'src', 'main', 'res', 'drawable')
OUT = os.path.join(HERE, '..', 'components', 'scanGuide', 'howtoDrawings.ts')


def colour(value):
    if value is None:
        return None, None
    v = value.lstrip('#')
    if len(v) == 8:  # AARRGGBB
        return '#' + v[2:], round(int(v[:2], 16) / 255, 3)
    return '#' + v, None


drawings = {}
for path in sorted(glob.glob(os.path.join(SRC, 'howto_*.xml'))):
    root = ET.parse(path).getroot()
    paths = []
    for p in root.iter('path'):
        fill, fill_a = colour(p.get(A + 'fillColor'))
        stroke, stroke_a = colour(p.get(A + 'strokeColor'))
        alpha = p.get(A + 'fillAlpha')
        entry = {'d': p.get(A + 'pathData'), 'fill': fill or 'none'}
        if alpha is not None or fill_a is not None:
            entry['fillOpacity'] = float(alpha) if alpha is not None else fill_a
        if stroke:
            entry['stroke'] = stroke
            if stroke_a is not None:
                entry['strokeOpacity'] = stroke_a
            entry['strokeWidth'] = float(p.get(A + 'strokeWidth') or '1')
            if p.get(A + 'strokeLineCap'):
                entry['strokeLinecap'] = p.get(A + 'strokeLineCap')
            if p.get(A + 'strokeLineJoin'):
                entry['strokeLinejoin'] = p.get(A + 'strokeLineJoin')
        paths.append(entry)
    name = os.path.splitext(os.path.basename(path))[0][len('howto_'):]
    drawings[name] = {'viewBox': '0 0 %s %s' % (root.get(A + 'viewportWidth'), root.get(A + 'viewportHeight')), 'paths': paths}
    print(name, len(paths), 'paths')

head = '''/**
 * GENERATED by scripts/howto-svgs.py from Scrivn Scan's own how-to drawings
 * (ARCapturePrototype/android/app/src/main/res/drawable/howto_*.xml). Do not edit by hand: change the
 * app's drawing and run the script again.
 */

export interface HowtoPath {
  d: string;
  fill: string;
  fillOpacity?: number;
  stroke?: string;
  strokeOpacity?: number;
  strokeWidth?: number;
  strokeLinecap?: "butt" | "round" | "square";
  strokeLinejoin?: "miter" | "round" | "bevel";
}

export interface HowtoDrawing {
  viewBox: string;
  paths: HowtoPath[];
}

export const HOWTO_DRAWINGS = '''
body = json.dumps(drawings, indent=2)
io.open(OUT, 'w', encoding='utf8', newline='\n').write(head + body + ' satisfies Record<string, HowtoDrawing>;\n\nexport type HowtoName = keyof typeof HOWTO_DRAWINGS;\n')
print('wrote', OUT)
