export { ceilingPaintLine, ceilingQuantity, primingLine, baseboardFinishLine } from "@/lib/paintDerivation";
export { buildWorkOrders } from "@/lib/workOrders";
export { emptyClaimInfo } from "@/lib/claimInfo";
export { withDerivedFields } from "@/lib/types";
export { surfaceThumbnails, surfaceRenderId, isSurfaceRender } from "@/lib/surfaceThumbnails";
export { availableRenders, pruneAttachments, sketchRenderLabel, sketchRenderDescription, parseRender, defaultSketchAttachments } from "@/lib/sketchAttachments";
export { PIXELS_PER_FOOT } from "@/lib/sketch";
export { emptyMoistureMap, roomMoisture, setRoomMoisture } from "@/lib/moisture";
export { resolveRound } from "@/lib/questionRound";
export { pruneScopeMarks, hasScopeMark, scopeWallRunFeet } from "@/lib/scopeMarks";
export { pruneMoisture, paintedFloorSquareFeet } from "@/lib/moisture";
