/**
 * GENERATED by scripts/howto-svgs.py from Scrivn Scan's own how-to drawings
 * (ARCapturePrototype/android/app/src/main/res/drawable/howto_*.xml). Do not edit by hand: change the
 * app's drawing and run the script again.
 */

export interface HowtoPath {
  d: string;
  fill: string;
  fillOpacity?: number;
  stroke?: string;
  strokeOpacity?: number;
  strokeWidth?: number;
  strokeLinecap?: "butt" | "round" | "square";
  strokeLinejoin?: "miter" | "round" | "bevel";
}

export interface HowtoDrawing {
  viewBox: string;
  paths: HowtoPath[];
}

export const HOWTO_DRAWINGS = {
  "cabinet": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M12,34 L74,34",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M18,34 L66,34 L66,50 L18,50 Z",
        "fill": "#1b3a5c",
        "fillOpacity": 0.12
      },
      {
        "d": "M18,34 L66,34 L66,50 L18,50 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.0,
        "strokeLinecap": "round"
      },
      {
        "d": "M14.4,34 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M62.4,34 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M92,58 L146,58 L146,86 L92,86 Z",
        "fill": "#1b3a5c",
        "fillOpacity": 0.12
      },
      {
        "d": "M92,58 L146,58 L146,86 L92,86 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.0,
        "strokeLinecap": "round"
      },
      {
        "d": "M88.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M142.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M115.4,58 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M119.0,86.0 L119.0,81.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M119.0,78.0 L119.0,73.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M119.0,70.0 L119.0,65.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M119.0,62.0 L119.0,58.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M84,72 l6,-5 l0,10 z",
        "fill": "none",
        "stroke": "#c97a0e",
        "strokeWidth": 1.0,
        "strokeLinecap": "round"
      }
    ]
  },
  "cant_reach": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M28,30 L28,86 L134,86",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,86.0 L28.0,80.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,76.0 L28.0,70.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,66.0 L28.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,56.0 L28.0,50.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,46.0 L28.0,40.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,36.0 L28.0,30.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,26.0 L28.0,24.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.0,86.0 L34.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M38.0,86.0 L44.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M48.0,86.0 L54.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M58.0,86.0 L64.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M68.0,86.0 L74.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M78.0,86.0 L84.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M88.0,86.0 L94.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M98.0,86.0 L104.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M108.0,86.0 L114.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M118.0,86.0 L124.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M128.0,86.0 L134.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M138.0,86.0 L144.0,86.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M24.4,44 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M24.4,66 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M66.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M102.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M19.5,86 a8.5,8.5 0 1,0 17.0,0 a8.5,8.5 0 1,0 -17.0,0",
        "fill": "none",
        "stroke": "#c97a0e",
        "strokeWidth": 2.0,
        "strokeLinecap": "round"
      }
    ]
  },
  "ceiling": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M16,96 L144,96",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M16,96 L16,62",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M144,96 L144,34",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M16,62 L80,30 L144,34",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M76.4,30 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M14.4,62 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M80.0,30.0 L80.0,35.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,39.0 L80.0,44.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,48.0 L80.0,53.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,57.0 L80.0,62.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,66.0 L80.0,71.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,75.0 L80.0,80.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,84.0 L80.0,89.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,93.0 L80.0,96.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M24.0,62.0 L24.0,67.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M24.0,71.0 L24.0,76.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M24.0,80.0 L24.0,85.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M24.0,89.0 L24.0,94.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      }
    ]
  },
  "corner": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M22,26 L138,26 L138,94 L22,94 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,60.0 L74.8,57.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M71.4,54.9 L66.2,51.9",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M62.7,49.9 L57.6,46.9",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M54.1,44.8 L48.9,41.8",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M45.5,39.8 L40.3,36.7",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M36.9,34.7 L31.7,31.7",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.2,29.7 L23.1,26.6",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,60.0 L85.2,57.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M88.6,54.9 L93.8,51.9",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M97.3,49.9 L102.4,46.9",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M105.9,44.8 L111.1,41.8",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M114.5,39.8 L119.7,36.7",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M123.1,34.7 L128.3,31.7",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M131.8,29.7 L136.9,26.6",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,60.0 L85.2,63.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M88.6,65.1 L93.8,68.1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M97.3,70.1 L102.4,73.1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M105.9,75.2 L111.1,78.2",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M114.5,80.2 L119.7,83.3",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M123.1,85.3 L128.3,88.3",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M131.8,90.3 L136.9,93.4",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,60.0 L74.8,63.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M71.4,65.1 L66.2,68.1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M62.7,70.1 L57.6,73.1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M54.1,75.2 L48.9,78.2",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M45.5,80.2 L40.3,83.3",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M36.9,85.3 L31.7,88.3",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28.2,90.3 L23.1,93.4",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M18.4,26 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M134.4,26 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M134.4,94 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M18.4,94 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M14.5,26 a7.5,7.5 0 1,0 15.0,0 a7.5,7.5 0 1,0 -15.0,0",
        "fill": "none",
        "stroke": "#c97a0e",
        "strokeWidth": 2.0,
        "strokeLinecap": "round"
      },
      {
        "d": "M75.8,60 a4.2,4.2 0 1,0 8.4,0 a4.2,4.2 0 1,0 -8.4,0",
        "fill": "#1b3a5c"
      },
      {
        "d": "M71.5,60 a8.5,8.5 0 1,0 17.0,0 a8.5,8.5 0 1,0 -17.0,0",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      }
    ]
  },
  "corner_unit": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M20,60 L32,60 L74,84 L74,96 L20,96 Z",
        "fill": "#dfe6ee"
      },
      {
        "d": "M20,20 L20,60 M74,96 L140,96",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M20,60 L32,60 L74,84 L74,96",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round",
        "strokeLinejoin": "round"
      },
      {
        "d": "M20,60 L20,96 L74,96",
        "fill": "none",
        "stroke": "#9aa6b4",
        "strokeWidth": 1.2,
        "strokeLinecap": "round"
      },
      {
        "d": "M16.4,60 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M28.4,60 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M70.4,84 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M70.4,96 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M42,50 L54,50 M60,50 L72,50 M78,50 L88,50",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M84,46 l6,4 l-6,4",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M20,44 L32,44 M20,41 L20,47 M32,41 L32,47",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M88,96 L88,84 M85,96 L91,96 M85,84 L91,84",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      }
    ]
  },
  "lost": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M24,26 L136,26 L136,86 L24,86 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinejoin": "round"
      },
      {
        "d": "M20.4,26 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M132.4,26 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M132.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M20.4,86 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M74,56 a6,6 0 1,0 12,0 a6,6 0 1,0 -12,0",
        "fill": "#1b3a5c"
      },
      {
        "d": "M60,44 L66,40 M70,36 L77,34 M83,34 L90,36 M94,40 L100,44 M102,49 L104,56",
        "fill": "none",
        "stroke": "#1e8449",
        "strokeWidth": 2.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M99,50 l5,6 l-7,3",
        "fill": "none",
        "stroke": "#1e8449",
        "strokeWidth": 2.4,
        "strokeLinecap": "round",
        "strokeLinejoin": "round"
      },
      {
        "d": "M77,52 L30,30 M83,52 L130,30",
        "fill": "none",
        "stroke": "#9aa6b4",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M24,100 L136,100",
        "fill": "none",
        "stroke": "#dfe6ee",
        "strokeWidth": 2.0
      }
    ]
  },
  "open_span": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M56,26 L104,26 L104,52 L56,52 Z",
        "fill": "#eef1f5"
      },
      {
        "d": "M56,32 L104,32 M56,38 L104,38 M56,44 L104,44",
        "fill": "none",
        "stroke": "#aab4c0",
        "strokeWidth": 1.4
      },
      {
        "d": "M20,96 L20,52 L56,52 M104,52 L140,52 L140,96",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 3.0,
        "strokeLinecap": "round",
        "strokeLinejoin": "round"
      },
      {
        "d": "M40,52 L56,52 M104,52 L120,52",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 6.0
      },
      {
        "d": "M58,52 L64,52 M69,52 L75,52 M80,52 L86,52 M91,52 L97,52 M100,52 L103,52",
        "fill": "none",
        "stroke": "#7b4ea8",
        "strokeWidth": 3.0,
        "strokeLinecap": "round"
      },
      {
        "d": "M52.4,52 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M100.4,52 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M64,66 L76,66 M82,66 L94,66",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M90,62 l6,4 l-6,4",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M28,78 L132,78 M28,88 L132,88",
        "fill": "none",
        "stroke": "#dfe6ee",
        "strokeWidth": 2.0
      }
    ]
  },
  "opening": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M16,70 L58,70",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M102,70 L144,70",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M54.4,70 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M98.4,70 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M58,70 q0,-30 44,-30",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.8,
        "strokeLinecap": "round"
      },
      {
        "d": "M58,70 L58,40",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.8,
        "strokeLinecap": "round"
      },
      {
        "d": "M58.0,84.0 L63.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M66.0,84.0 L71.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M74.0,84.0 L79.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M82.0,84.0 L87.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M90.0,84.0 L95.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M98.0,84.0 L102.0,84.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M58,80 L58,88",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M102,80 L102,88",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      }
    ]
  },
  "review": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M30,38 L118,38 L118,92 L30,92 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M58,16 L120,16 L120,32 L58,32 Z",
        "fill": "#ffffff"
      },
      {
        "d": "M58,16 L120,16 L120,32 L58,32 Z",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M66,24 L96,24",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.2,
        "strokeLinecap": "round"
      },
      {
        "d": "M88.0,32.0 L84.4,33.8",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M81.7,35.1 L78.2,36.9",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M97,40 a9,9 0 1,0 18,0 a9,9 0 1,0 -18,0",
        "fill": "none",
        "stroke": "#c97a0e",
        "strokeWidth": 2.2,
        "strokeLinecap": "round"
      },
      {
        "d": "M103.4,40 a2.6,2.6 0 1,0 5.2,0 a2.6,2.6 0 1,0 -5.2,0",
        "fill": "#c97a0e"
      }
    ]
  },
  "send": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M20,34 L46,34 L46,86 L20,86 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M25,40 L41,40",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M52.0,60.0 L58.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M62.0,60.0 L68.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M72.0,60.0 L78.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M82.0,60.0 L88.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M92.0,60.0 L96.0,60.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M88,55 l7,5 l-7,5",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.8,
        "strokeLinecap": "round"
      },
      {
        "d": "M104,30 L144,30 L144,90 L104,90 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M112,44 L136,44",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M112,56 L136,56",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M112,68 L126,68",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M123.9,60 a0.1,0.1 0 1,0 0.2,0 a0.1,0.1 0 1,0 -0.2,0",
        "fill": "#ffffff"
      }
    ]
  },
  "stairs": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M34,84 L126,84",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M34,40 L126,40",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M34.0,84.0 L34.0,79.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M34.0,75.0 L34.0,70.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M34.0,66.0 L34.0,61.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M34.0,57.0 L34.0,52.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M34.0,48.0 L34.0,43.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M126.0,84.0 L126.0,79.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M126.0,75.0 L126.0,70.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M126.0,66.0 L126.0,61.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M126.0,57.0 L126.0,52.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M126.0,48.0 L126.0,43.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M52,74 L108,74",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M52,63 L108,63",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M52,52 L108,52",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.4,
        "strokeLinecap": "round"
      },
      {
        "d": "M30.4,84 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M122.4,84 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M122.4,40 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M30.4,40 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      }
    ]
  },
  "start": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M70,40 L90,40 L90,82 L70,82 Z",
        "fill": "#ffffff"
      },
      {
        "d": "M70,40 L90,40 L90,82 L70,82 Z",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M74,45 L86,45",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M60.0,96.0 L66.0,96.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M70.0,96.0 L76.0,96.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M80.0,96.0 L86.0,96.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M90.0,96.0 L96.0,96.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M52,61 q-10,-14 6,-20",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M108,61 q10,-14 -6,-20",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M56,36 l2,5 l-5,1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M104,36 l-2,5 l5,1",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M71,61 a9,9 0 1,0 18,0 a9,9 0 1,0 -18,0",
        "fill": "none",
        "stroke": "#33E06A",
        "strokeWidth": 2.4,
        "strokeLinecap": "round"
      }
    ]
  },
  "wall_end": {
    "viewBox": "0 0 160 120",
    "paths": [
      {
        "d": "M20,24 L20,96 L140,96",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M20,52 L96,52 M20,60 L96,60",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M96,52 L96,60",
        "fill": "none",
        "stroke": "#1b3a5c",
        "strokeWidth": 2.5,
        "strokeLinecap": "round"
      },
      {
        "d": "M92.4,56 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0",
        "fill": "#c97a0e"
      },
      {
        "d": "M104.0,56.0 L109.0,56.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M112.0,56.0 L117.0,56.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M120.0,56.0 L125.0,56.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M128.0,56.0 L132.0,56.0",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      },
      {
        "d": "M124,52 l6,4 l-6,4",
        "fill": "none",
        "stroke": "#5b6472",
        "strokeWidth": 1.6,
        "strokeLinecap": "round"
      }
    ]
  }
} satisfies Record<string, HowtoDrawing>;

export type HowtoName = keyof typeof HOWTO_DRAWINGS;
